# Generated by Django 3.0.2 on 2020-01-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200105_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_worold',
            new_name='fees_in_world',
        ),
    ]
